[Main]
Title=OCCT - File Container
Type=XPEPlugin
Description=OCCT v5.4.2.99 File Container
Author=KYHI
Date=2019.12.06
Credits=TheOven.org Forum
Contact=
Version=001
Level=0
Download_Level=2
Selected=None
Mandatory=False
NoWarning=False
History001=KYHI Initial XPE Packed Container Plugin Created 2019.12.06
History002=

[Interface]
Hide_TextBox="To Hide Plugin From Tree - Edit Container File Plugin [Main] Level=5 to Level=0",1,1,10,60,531,18,8,Bold

[Variables]

[Process]
Echo,"File Container Plugin - There Is Nothing To Process"

[AuthorEncoded]
OCCT54848.ico=300,400
Logo=OCCT54848.ico

[EncodedFile-AuthorEncoded-OCCT54848.ico]
lines=0
0=eJzt1jEOgkAQBdBvIa1UttqQWHIDr+JNsOYkHs/SgrjOYjbGQsVBZifyhwwTKMj7GwILLOSoa8h5i1MFrAHspOUWDrjfj3WsMLcKTlptL8s2ayszuLArM7iyKzJkt37IQD/99NNPP/2z92PEvtKRX1P0008//fTTTz/9bvyK9uS3KvrzFv0vnmvVHr6flk0//fTTT/90/mVRqP4tRvah+wdXGb60u8qgtLvIMNL+lCFj/3WFvoBrvGiALs49cIlzA5zjXE05m85iSsi389e50vql9Uzr279Q4bHuNxFgsER4nOP1d3YOMTWxMLHQy0zOZxgFIwzsU4XQD3DIqzRPFGRgAgAM7ga7dWtPSAEAAAACAAAAKAAAAOAAAAAAAAAAAQAAAAAAAAAAAAAA

[EncodedFolders]
Folder

[Folder]

