[Main]
Title=KS-Soft Network Management Software - File Container
Type=XPEPlugin
Description=KS-Soft Network Management Software File Container
Author=KYHI
Date=2020.02.08
Credits=TheOven.org Forum
Contact=
Version=001
Level=0
Download_Level=2
Selected=None
Mandatory=False
NoWarning=False
History001=KYHI Initial XPE Packed Container Plugin Created 2020.02.08
History002=

[Interface]
Hide_TextBox="To Hide Plugin From Tree - Edit Container File Plugin [Main] Level=5 to Level=0",1,1,10,60,531,18,8,Bold

[Variables]

[Process]
Echo,"File Container Plugin - There Is Nothing To Process"

[AuthorEncoded]
HostMon4848.ico=317,423
Logo=HostMon4848.ico

[EncodedFile-AuthorEncoded-HostMon4848.ico]
lines=0
0=eJztmM0NgzAMhV+X6LkXpB4ZqaMwTsfIZm2qKlJ/QmJIJNvhGT0IVog/OxZIAKd4zDPi+YL7BJwBXKOiCze8/S9bJvzZAjy8y6tp162XQghf1zSW3n/6Jeu0xq3xl+a3zpH6JHO38kvGUta1/dvLX1uv1iPSOuTi9K5/ru9ysWvjrf3/W0cJRy23NUn6Z49anqXGk/fvJPn12b3mQH7yk98/v9ccyH8s/t7/Mkr8vWP1qnPJX8pHWzmeUfmtsZPfhkr9PgK/ZXby21DtHe+F3zon+e0qmTYH+fVZjsifctBmODI/RXkQaKr2BFXrrzt4nOP3yC8u8c3PM7EwsdDLTM5nGAUjCuxThdDvcci3iZbuZGACABKcCLZyHWIeAQAAAAIAAAAqAAAA7wAAAAAAAAABAAAAAAAAAAAAAAA

[EncodedFolders]
Folder

[Folder]

