[Main]
Title=PuTTY - File Container
Type=XPEPlugin
Description=PuTTY Version  File Container
Author=JohnC
Date=2019.03.23
Credits=
Contact=
Version=002
Level=0
Download_Level=2
Selected=None
Mandatory=False
NoWarning=False
History001=JohnC Initial XPE AutoUpdate Plugin Created 2018.11.27
History002=KYHI Edit To Use Latest Download - 2019.03.23

[Interface]
Hide_TextBox="To Hide Plugin From Tree - Edit Container File Plugin [Main] Level=5 to Level=0",1,1,10,60,540,18,8,Bold
Update_TextBox="To Update This Container File - Just Press The Little GREEN Play Button",1,1,10,30,540,18,8,Bold

[Variables]
%ProgramTitle%=PuTTY
%ProgramFolder%=PuTTY
%SetupFile%=putty.zip
%SetupFilex64%=putty64.zip
%File_Plugin%=%ScriptDir%\putty_XPE.Script
%File_Container%=%ScriptDir%\putty_XPE_File.Script
%ProvideFiles%=%ProgCache%\%ProgramFolder%
%SetupURL%=https://the.earth.li/~sgtatham/putty/latest/w32/putty.zip
%SetupURLx64%=https://the.earth.li/~sgtatham/putty/latest/w64/putty.zip

[Process]
Echo,"Update %ScriptTitle%..."
If,ExistDir,%ProvideFiles%,DirDeleteQ,%ProvideFiles%
If,Not,ExistDir,%ProvideFiles%,DirMake,%ProvideFiles%
//--
Run,%ScriptFile%,Download
//--
IniRead,%File_Plugin%,Main,Version,%Script_Version%
StrFormat,INC,%Script_Version%,1
Set,%History%,History%Script_Version%
Set,%NewVersion%,%Script_Version%
If,%Script_Version%,SMALLER,100,Set,%NewVersion%,0%Script_Version%
If,%Script_Version%,SMALLER,10,Set,%NewVersion%,00%Script_Version%
If,%Script_Version%,SMALLER,100,Set,%History%,History0%Script_Version%
If,%Script_Version%,SMALLER,10,Set,%History%,History00%Script_Version%
Retrieve,FileVersion,%ProvideFiles%\%SetupFile%,%ContainerVer%
StrFormat,DATE,%MyDate%,yyyy.mm.dd
//--
//-- Update Container File Attachment
IniWrite,%File_Container%,Main,Description," %ProgramTitle% Version %ContainerVer% File Container"
IniWrite,%File_Container%,Main,%History%," %UserName% - Auto Updated Container v%ContainerVer% - %MyDate%"
IniWrite,%File_Container%,Main,Date,%MyDate%
IniWrite,%File_Container%,Main,Version,%NewVersion%
IniWrite,%File_Container%,Main,Level,0
//--
//-- Update Plugin File Information
IniWrite,%File_Plugin%,Main,Description," Plugin Adds %ProgramTitle% Version %ContainerVer%"
IniWrite,%File_Plugin%,Main,%History%," %UserName% - Auto Updated Container v%ContainerVer% - %MyDate%"
IniWrite,%File_Plugin%,Main,Date,%MyDate%
IniWrite,%File_Plugin%,Main,Version,%NewVersion%
//--
DirDeleteQ,%ProvideFiles%
System,RefreshInterface

[Download]
If,Not,ExistDir,%ProvideFiles%,DirMake,%ProvideFiles%
Download,%ProvideFiles%\%SetupFile%,%SetupURL%
Encode,%File_Container%,Folder,%ProvideFiles%\%SetupFile%
//--
If,Not,%SetupFilex64%-,Equal,-,Begin
If,Not,%SetupURLx64%-,Equal,-,Begin
Download,%ProvideFiles%\%SetupFilex64%,%SetupURLx64%
Encode,%File_Container%,Folder,%ProvideFiles%\%SetupFilex64%
End
End

[AuthorEncoded]
Putty4848.ico=564,752
Logo=Putty4848.ico

[InterfaceEncoded]

[EncodedFolders]
Folder

[Folder]

[EncodedFile-AuthorEncoded-Putty4848.ico]
lines=0
0=eJztmk2SgjAUhHvKxSzdzVY3Vs3SG8xV5ig5zhyDo3gEli4sMwReMAQCBJKXpMpnte0PhV+TBEMU+Ghu1yua+zP+LsAXgO9GzUv4Rfe6KnGBqySDYpWsqqqVECKaImZg4Y+YQerSOdbKYJrU1DGJkEHGLIYMUfmnMgTmbzPoPoGA5xy1P10c40DzhxrLrgyR+EH77dt8q5YyROSHyb+1HOOV47us528/Wz32lZufq978b/5o/NDnqJL5pXRnyJx/MUMB/HYGZMw/pz4D5RC58a+9JjEyMM35F/l9ys6glJC/zeA7Zxtk0P0pHf/2DPaYSMePnmeLrP7Ej766ljMMc+xVWHaTcUnWuM5kDWZ8rMvLAN8MMM4Pjmu0wXbZtYOeP60srnWkUYaZ4+pbXOtIsNti5zkn1TrSVIat4zXVOtIgg3zN8UpaR8JEW6wpx3jl+k5/McC65tEZ5uTm56oRv1eGTPkljPafy5Ax/6gtCuWfzVAIv9mfSuUvtf+XxO+rrPg3qMR1JLsY5suLGfb8DmjP4xLwB82QiB8w5wz7NCoB/MjunRP5kfyT/GC6IK/Ib+Q1bV/T/kL7nfxB/iRv2Y6NPxUxPT8or9QfnzqH6TfymvxO/qDtH93+gvuTXGoXOAH/i+hI5nic4w0oLSmpNLEwsdDLTM5nGAUjDOxThdDPGbHLd3W2bWBgAgC9AwiLkKS14QEAAAACAAAAKQAAAOcBAAAAAAAAAQAAAAAAAAAAAAAA

